### PR TITLE
feat(schema): autogenerate the description in models using table name

### PR DESCRIPTION
**Pull request by benomatis**
It’s probably best as these models represent the table anyway.

### CODE REVIEW

**Comment by benomatis** [comment]
There might be more elegant ways of doing this, like NOT defining `name = ucfirst(name)+'.js';` before the `writeFile` function, but only inside somewhere (or add a new variable that would store the name with the `js` extension.

**Comment by RWOverdijk** [comment]
That could work I suppose. It's a template, so it's more flexible in coding style. If you want this in I'll merge it and publish :)

**Comment by benomatis** [comment]
Well I guess it's a question of preference; I use it this way, but it may benefit others, so I leave it up to you. ;)

**Comment by RWOverdijk** [comment]
Published both :)

**Comment by benomatis** [comment]
Cheers ;)

**Pull request merged**
